apiVersion: v1
kind: Secret
metadata:
  name: pg-admin-secrets
type: Opaque
data:
  # echo -n 'postgres' | base64
  PG_USER_EMAIL: dGVzdDFAdGVzdC5jb20=  # base64 for 'test1@test.com'
  DB_PASSWORD: c2VjcmV0cGFzc3dvcmQ=  # base64 for 'secretpassword'
