apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
data:
  # echo -n 'postgres' | base64
  DB_USER: cG9zdGdyZXM=  # base64 for 'postgres'
  DB_PASSWORD: cGFzc3dvcmQ=  # base64 for 'password
